### ISSUE TITLE
CodySystems Names

### ISSUE THREAD

**Issue by aslgraefe** [BIH-CEI/rarelink_phenopacket_mapper#101]
We should have consistency in the `name` of all ontologies used. 

e.g. ORDO should be:
```
ORDO = CodeSystem(
    name="Orphanet Rare Disease Ontology",
    namespace_prefix="ORPHA",
    url="http://www.orpha.net/"
```

we can take the official names and official namespace_prefixes from OLS: 
https://www.ebi.ac.uk/ols4/ontologies

**Comment by aslgraefe** [comment]
also the RareLink test `text_preprocess_redcap_code.py` is importing the CodeSystems from Phenopacket_mapper. But in there are not the ones I added in my notebook. where do we gather the added RareLink ontologies to import for a test.

I will comment these out for now in my test - but we'll need to add them somewhere. let me know where you want to have those

**Comment by frehburg** [comment]
Hey Adam, the `CodeSystem` class provides functionality to define new ontologies. Could you please create a pull request and add the missing ontologies in `code_system.py`?
