### ISSUE TITLE
Change "about" link from stable to latest

### ISSUE THREAD

**Issue by cmungall** [BIH-CEI/rarelink_phenopacket_mapper#139]
The "about" link here https://github.com/BIH-CEI/phenopacket_mapper

goes to https://bih-cei.github.io/phenopacket_mapper/stable/# which is very nice api docs, but not much else

I think it should point here? https://bih-cei.github.io/phenopacket_mapper/latest/

**Comment by frehburg** [comment]
Dear Chris, thanks for catching this
